export type ApiResponse_Properties_Status = "success" | "error" | "pending";

export type ApiResponse_Properties_Meta = ApiResponse_X24Defs_UResponseMeta;

export type ApiResponse_Properties_ErrorCode_AnyOf_ZIndex1 = null;

export type ApiResponse_Properties_ErrorCode_AnyOf_ZIndex0 = string;

export type ApiResponse_Properties_ErrorCode =
  ApiResponse_Properties_ErrorCode_AnyOf_ZIndex0 |
  ApiResponse_Properties_ErrorCode_AnyOf_ZIndex1;

export type ApiResponse_Properties_Data = ApiResponse_X24Defs_UPaginatedResult;

export type ApiResponse_AdditionalProperties = never;

export type ApiResponse_X24Defs_UResponseMeta_Properties_Version = string;

export type ApiResponse_X24Defs_UResponseMeta_Properties_Timestamp = string;

export type ApiResponse_X24Defs_UResponseMeta_Properties_RequestId = string;

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_SuggestedAlternative_AnyOf_ZIndex1 = null;

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_SuggestedAlternative_AnyOf_ZIndex0 = string;

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_SuggestedAlternative =
  ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_SuggestedAlternative_AnyOf_ZIndex0 |
  ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_SuggestedAlternative_AnyOf_ZIndex1;

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_Message = string;

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_Field = string;

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items {
  "message": ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_Message;
  "field": ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_Field;
  "suggestedAlternative"?: ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items_Properties_SuggestedAlternative;
}

export type ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings = ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings_Items[];

export type ApiResponse_X24Defs_UResponseMeta_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UResponseMeta {
  "requestId": ApiResponse_X24Defs_UResponseMeta_Properties_RequestId;
  "timestamp": ApiResponse_X24Defs_UResponseMeta_Properties_Timestamp;
  "version"?: ApiResponse_X24Defs_UResponseMeta_Properties_Version;
  "deprecationWarnings"?: ApiResponse_X24Defs_UResponseMeta_Properties_DeprecationWarnings;
}

export type ApiResponse_X24Defs_UPaginationInfo_Properties_TotalPages = number;

export type ApiResponse_X24Defs_UPaginationInfo_Properties_TotalItems = number;

export type ApiResponse_X24Defs_UPaginationInfo_Properties_PageSize = number;

export type ApiResponse_X24Defs_UPaginationInfo_Properties_Page = number;

export type ApiResponse_X24Defs_UPaginationInfo_Properties_HasPreviousPage = boolean;

export type ApiResponse_X24Defs_UPaginationInfo_Properties_HasNextPage = boolean;

export type ApiResponse_X24Defs_UPaginationInfo_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UPaginationInfo {
  "page": ApiResponse_X24Defs_UPaginationInfo_Properties_Page;
  "pageSize": ApiResponse_X24Defs_UPaginationInfo_Properties_PageSize;
  "totalItems": ApiResponse_X24Defs_UPaginationInfo_Properties_TotalItems;
  "totalPages": ApiResponse_X24Defs_UPaginationInfo_Properties_TotalPages;
  "hasNextPage"?: ApiResponse_X24Defs_UPaginationInfo_Properties_HasNextPage;
  "hasPreviousPage"?: ApiResponse_X24Defs_UPaginationInfo_Properties_HasPreviousPage;
}

export type ApiResponse_X24Defs_UPaginatedResult_Properties_Pagination = ApiResponse_X24Defs_UPaginationInfo;

export type ApiResponse_X24Defs_UPaginatedResult_Properties_Items_Items = ApiResponse_X24Defs_UEntity;

export type ApiResponse_X24Defs_UPaginatedResult_Properties_Items = ApiResponse_X24Defs_UPaginatedResult_Properties_Items_Items[];

export type ApiResponse_X24Defs_UPaginatedResult_Properties_Filters = ApiResponse_X24Defs_UAppliedFilters;

export type ApiResponse_X24Defs_UPaginatedResult_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UPaginatedResult {
  "items": ApiResponse_X24Defs_UPaginatedResult_Properties_Items;
  "pagination": ApiResponse_X24Defs_UPaginatedResult_Properties_Pagination;
  "filters"?: ApiResponse_X24Defs_UPaginatedResult_Properties_Filters;
}

export type ApiResponse_X24Defs_UEntityReference_Properties_Type = string;

export type ApiResponse_X24Defs_UEntityReference_Properties_Id = string;

export type ApiResponse_X24Defs_UEntityReference_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UEntityReference {
  "id": ApiResponse_X24Defs_UEntityReference_Properties_Id;
  "type": ApiResponse_X24Defs_UEntityReference_Properties_Type;
}

export type ApiResponse_X24Defs_UEntityAttributes_Properties_X75pdatedAt_AnyOf_ZIndex1 = null;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_X75pdatedAt_AnyOf_ZIndex0 = string;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_X75pdatedAt =
  ApiResponse_X24Defs_UEntityAttributes_Properties_X75pdatedAt_AnyOf_ZIndex0 |
  ApiResponse_X24Defs_UEntityAttributes_Properties_X75pdatedAt_AnyOf_ZIndex1;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Tags_Items = string;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Tags = ApiResponse_X24Defs_UEntityAttributes_Properties_Tags_Items[];

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Name = string;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties_AnyOf_ZIndex2 = boolean;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties_AnyOf_ZIndex1 = number;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties_AnyOf_ZIndex0 = string;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties =
  ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties_AnyOf_ZIndex0 |
  ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties_AnyOf_ZIndex1 |
  ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties_AnyOf_ZIndex2;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata = Record<string, ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata_AdditionalProperties>;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Description_AnyOf_ZIndex1 = null;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Description_AnyOf_ZIndex0 = string;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_Description =
  ApiResponse_X24Defs_UEntityAttributes_Properties_Description_AnyOf_ZIndex0 |
  ApiResponse_X24Defs_UEntityAttributes_Properties_Description_AnyOf_ZIndex1;

export type ApiResponse_X24Defs_UEntityAttributes_Properties_CreatedAt = string;

export type ApiResponse_X24Defs_UEntityAttributes_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UEntityAttributes {
  "name": ApiResponse_X24Defs_UEntityAttributes_Properties_Name;
  "description"?: ApiResponse_X24Defs_UEntityAttributes_Properties_Description;
  "createdAt": ApiResponse_X24Defs_UEntityAttributes_Properties_CreatedAt;
  "updatedAt"?: ApiResponse_X24Defs_UEntityAttributes_Properties_X75pdatedAt;
  "tags"?: ApiResponse_X24Defs_UEntityAttributes_Properties_Tags;
  "metadata"?: ApiResponse_X24Defs_UEntityAttributes_Properties_Metadata;
}

export type ApiResponse_X24Defs_UEntity_Properties_Type = "user" | "organization" | "resource";

export type ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Parent = ApiResponse_X24Defs_UEntityReference;

export type ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Children_Items = ApiResponse_X24Defs_UEntityReference;

export type ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Children = ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Children_Items[];

export type ApiResponse_X24Defs_UEntity_Properties_Relationships_AdditionalProperties = ApiResponse_X24Defs_UEntityReference;

export interface ApiResponse_X24Defs_UEntity_Properties_Relationships {
  "parent"?: ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Parent;
  "children"?: ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Children;
  [key: string]:
    ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Parent |
    ApiResponse_X24Defs_UEntity_Properties_Relationships_Properties_Children |
    ApiResponse_X24Defs_UEntity_Properties_Relationships_AdditionalProperties |
    undefined;
}

export type ApiResponse_X24Defs_UEntity_Properties_Id = string;

export type ApiResponse_X24Defs_UEntity_Properties_Attributes = ApiResponse_X24Defs_UEntityAttributes;

export type ApiResponse_X24Defs_UEntity_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UEntity {
  "id": ApiResponse_X24Defs_UEntity_Properties_Id;
  "type": ApiResponse_X24Defs_UEntity_Properties_Type;
  "attributes": ApiResponse_X24Defs_UEntity_Properties_Attributes;
  "relationships"?: ApiResponse_X24Defs_UEntity_Properties_Relationships;
}

export type ApiResponse_X24Defs_UAppliedFilters_Properties_Types_Items = "user" | "organization" | "resource";

export type ApiResponse_X24Defs_UAppliedFilters_Properties_Types = ApiResponse_X24Defs_UAppliedFilters_Properties_Types_Items[];

export type ApiResponse_X24Defs_UAppliedFilters_Properties_SortOrder = "asc" | "desc";

export type ApiResponse_X24Defs_UAppliedFilters_Properties_SortBy = "name" | "createdAt" | "updatedAt" | null;

export type ApiResponse_X24Defs_UAppliedFilters_Properties_Search_AnyOf_ZIndex1 = null;

export type ApiResponse_X24Defs_UAppliedFilters_Properties_Search_AnyOf_ZIndex0 = string;

export type ApiResponse_X24Defs_UAppliedFilters_Properties_Search =
  ApiResponse_X24Defs_UAppliedFilters_Properties_Search_AnyOf_ZIndex0 |
  ApiResponse_X24Defs_UAppliedFilters_Properties_Search_AnyOf_ZIndex1;

export type ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange_Properties_Start = string;

export type ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange_Properties_End = string;

export type ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange {
  "start": ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange_Properties_Start;
  "end": ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange_Properties_End;
}

export type ApiResponse_X24Defs_UAppliedFilters_AdditionalProperties = never;

export interface ApiResponse_X24Defs_UAppliedFilters {
  "search"?: ApiResponse_X24Defs_UAppliedFilters_Properties_Search;
  "dateRange"?: ApiResponse_X24Defs_UAppliedFilters_Properties_DateRange;
  "types"?: ApiResponse_X24Defs_UAppliedFilters_Properties_Types;
  "sortBy"?: ApiResponse_X24Defs_UAppliedFilters_Properties_SortBy;
  "sortOrder"?: ApiResponse_X24Defs_UAppliedFilters_Properties_SortOrder;
}

export interface ApiResponse {
  "status": ApiResponse_Properties_Status;
  "errorCode"?: ApiResponse_Properties_ErrorCode;
  "data": ApiResponse_Properties_Data;
  "meta": ApiResponse_Properties_Meta;
}
