export type DocSystem_Properties_RelatedDocuments_Items_Properties_Title_AnyOf_ZIndex1 = null;

export type DocSystem_Properties_RelatedDocuments_Items_Properties_Title_AnyOf_ZIndex0 = string;

export type DocSystem_Properties_RelatedDocuments_Items_Properties_Title =
  DocSystem_Properties_RelatedDocuments_Items_Properties_Title_AnyOf_ZIndex0 |
  DocSystem_Properties_RelatedDocuments_Items_Properties_Title_AnyOf_ZIndex1;

export type DocSystem_Properties_RelatedDocuments_Items_Properties_Relationship = "parent" | "child" | "sibling" | "reference";

export type DocSystem_Properties_RelatedDocuments_Items_Properties_Id = DocSystem_X24Defs_X55X55ID;

export type DocSystem_Properties_RelatedDocuments_Items_AdditionalProperties = never;

export interface DocSystem_Properties_RelatedDocuments_Items {
  "id": DocSystem_Properties_RelatedDocuments_Items_Properties_Id;
  "relationship": DocSystem_Properties_RelatedDocuments_Items_Properties_Relationship;
  "title"?: DocSystem_Properties_RelatedDocuments_Items_Properties_Title;
}

export type DocSystem_Properties_RelatedDocuments = DocSystem_Properties_RelatedDocuments_Items[];

export type DocSystem_Properties_Permissions_Properties_Readers_Items = DocSystem_X24Defs_X55ser;

export type DocSystem_Properties_Permissions_Properties_Readers = DocSystem_Properties_Permissions_Properties_Readers_Items[];

export type DocSystem_Properties_Permissions_Properties_Owner = DocSystem_X24Defs_X55ser;

export type DocSystem_Properties_Permissions_Properties_IsPublic = boolean;

export type DocSystem_Properties_Permissions_Properties_ExpiresAt_AnyOf_ZIndex1 = null;

export type DocSystem_Properties_Permissions_Properties_ExpiresAt_AnyOf_ZIndex0 = DocSystem_X24Defs_UTimestamp;

export type DocSystem_Properties_Permissions_Properties_ExpiresAt =
  DocSystem_Properties_Permissions_Properties_ExpiresAt_AnyOf_ZIndex0 |
  DocSystem_Properties_Permissions_Properties_ExpiresAt_AnyOf_ZIndex1;

export type DocSystem_Properties_Permissions_Properties_Editors_Items = DocSystem_X24Defs_X55ser;

export type DocSystem_Properties_Permissions_Properties_Editors = DocSystem_Properties_Permissions_Properties_Editors_Items[];

export type DocSystem_Properties_Permissions_AdditionalProperties = never;

export interface DocSystem_Properties_Permissions {
  "owner": DocSystem_Properties_Permissions_Properties_Owner;
  "readers": DocSystem_Properties_Permissions_Properties_Readers;
  "editors": DocSystem_Properties_Permissions_Properties_Editors;
  "isPublic"?: DocSystem_Properties_Permissions_Properties_IsPublic;
  "expiresAt"?: DocSystem_Properties_Permissions_Properties_ExpiresAt;
}

export type DocSystem_Properties_History_Items_Properties_Timestamp = DocSystem_X24Defs_UTimestamp;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex1 = null;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue_AnyOf_ZIndex2 = null;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue_AnyOf_ZIndex1 = number;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue_AnyOf_ZIndex0 = string;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue =
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue_AnyOf_ZIndex0 |
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue_AnyOf_ZIndex1 |
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue_AnyOf_ZIndex2;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue_AnyOf_ZIndex2 = null;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue_AnyOf_ZIndex1 = number;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue_AnyOf_ZIndex0 = string;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue =
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue_AnyOf_ZIndex0 |
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue_AnyOf_ZIndex1 |
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue_AnyOf_ZIndex2;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_Field = string;

export type DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_AdditionalProperties = never;

export interface DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0 {
  "field"?: DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_Field;
  "oldValue"?: DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_OldValue;
  "newValue"?: DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0_Properties_NewValue;
}

export type DocSystem_Properties_History_Items_Properties_Details =
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex0 |
  DocSystem_Properties_History_Items_Properties_Details_AnyOf_ZIndex1;

export type DocSystem_Properties_History_Items_Properties_Actor = DocSystem_X24Defs_X55ser;

export type DocSystem_Properties_History_Items_Properties_Action = "created" | "updated" | "deleted" | "restored" | "shared";

export type DocSystem_Properties_History_Items_AdditionalProperties = never;

export interface DocSystem_Properties_History_Items {
  "action": DocSystem_Properties_History_Items_Properties_Action;
  "actor": DocSystem_Properties_History_Items_Properties_Actor;
  "timestamp": DocSystem_Properties_History_Items_Properties_Timestamp;
  "details"?: DocSystem_Properties_History_Items_Properties_Details;
}

export type DocSystem_Properties_History = DocSystem_Properties_History_Items[];

export type DocSystem_Properties_Document_Properties_Title = string;

export type DocSystem_Properties_Document_Properties_Tags_Items_Properties_Name = string;

export type DocSystem_Properties_Document_Properties_Tags_Items_Properties_Color_AnyOf_ZIndex1 = null;

export type DocSystem_Properties_Document_Properties_Tags_Items_Properties_Color_AnyOf_ZIndex0 = string;

export type DocSystem_Properties_Document_Properties_Tags_Items_Properties_Color =
  DocSystem_Properties_Document_Properties_Tags_Items_Properties_Color_AnyOf_ZIndex0 |
  DocSystem_Properties_Document_Properties_Tags_Items_Properties_Color_AnyOf_ZIndex1;

export type DocSystem_Properties_Document_Properties_Tags_Items_AdditionalProperties = never;

export interface DocSystem_Properties_Document_Properties_Tags_Items {
  "name": DocSystem_Properties_Document_Properties_Tags_Items_Properties_Name;
  "color"?: DocSystem_Properties_Document_Properties_Tags_Items_Properties_Color;
}

export type DocSystem_Properties_Document_Properties_Tags = DocSystem_Properties_Document_Properties_Tags_Items[];

export type DocSystem_Properties_Document_Properties_Reviewers_Items = DocSystem_X24Defs_X55ser;

export type DocSystem_Properties_Document_Properties_Reviewers = DocSystem_Properties_Document_Properties_Reviewers_Items[];

export type DocSystem_Properties_Document_Properties_Metadata_Properties_Version = number;

export type DocSystem_Properties_Document_Properties_Metadata_Properties_X75pdatedAt = DocSystem_X24Defs_UTimestamp;

export type DocSystem_Properties_Document_Properties_Metadata_Properties_CreatedAt = DocSystem_X24Defs_UTimestamp;

export type DocSystem_Properties_Document_Properties_Metadata_AdditionalProperties = never;

export interface DocSystem_Properties_Document_Properties_Metadata {
  "createdAt"?: DocSystem_Properties_Document_Properties_Metadata_Properties_CreatedAt;
  "updatedAt"?: DocSystem_Properties_Document_Properties_Metadata_Properties_X75pdatedAt;
  "version"?: DocSystem_Properties_Document_Properties_Metadata_Properties_Version;
}

export type DocSystem_Properties_Document_Properties_Id = DocSystem_X24Defs_X55X55ID;

export type DocSystem_Properties_Document_Properties_Content_Properties_Summary_AnyOf_ZIndex1 = null;

export type DocSystem_Properties_Document_Properties_Content_Properties_Summary_AnyOf_ZIndex0 = string;

export type DocSystem_Properties_Document_Properties_Content_Properties_Summary =
  DocSystem_Properties_Document_Properties_Content_Properties_Summary_AnyOf_ZIndex0 |
  DocSystem_Properties_Document_Properties_Content_Properties_Summary_AnyOf_ZIndex1;

export type DocSystem_Properties_Document_Properties_Content_Properties_Format = "markdown" | "html" | "plaintext";

export type DocSystem_Properties_Document_Properties_Content_Properties_Body = string;

export type DocSystem_Properties_Document_Properties_Content_AdditionalProperties = never;

export interface DocSystem_Properties_Document_Properties_Content {
  "format": DocSystem_Properties_Document_Properties_Content_Properties_Format;
  "body": DocSystem_Properties_Document_Properties_Content_Properties_Body;
  "summary"?: DocSystem_Properties_Document_Properties_Content_Properties_Summary;
}

export type DocSystem_Properties_Document_Properties_Author = DocSystem_X24Defs_X55ser;

export type DocSystem_Properties_Document_AdditionalProperties = never;

export interface DocSystem_Properties_Document {
  "id": DocSystem_Properties_Document_Properties_Id;
  "title": DocSystem_Properties_Document_Properties_Title;
  "content": DocSystem_Properties_Document_Properties_Content;
  "author": DocSystem_Properties_Document_Properties_Author;
  "reviewers"?: DocSystem_Properties_Document_Properties_Reviewers;
  "tags"?: DocSystem_Properties_Document_Properties_Tags;
  "metadata"?: DocSystem_Properties_Document_Properties_Metadata;
}

export type DocSystem_AdditionalProperties = never;

export type DocSystem_X24Defs_X55ser_Properties_Role = "admin" | "editor" | "viewer" | "guest";

export type DocSystem_X24Defs_X55ser_Properties_Id = DocSystem_X24Defs_X55X55ID;

export type DocSystem_X24Defs_X55ser_Properties_Email = string;

export type DocSystem_X24Defs_X55ser_Properties_DisplayName_AnyOf_ZIndex1 = null;

export type DocSystem_X24Defs_X55ser_Properties_DisplayName_AnyOf_ZIndex0 = string;

export type DocSystem_X24Defs_X55ser_Properties_DisplayName =
  DocSystem_X24Defs_X55ser_Properties_DisplayName_AnyOf_ZIndex0 |
  DocSystem_X24Defs_X55ser_Properties_DisplayName_AnyOf_ZIndex1;

export type DocSystem_X24Defs_X55ser_AdditionalProperties = never;

export interface DocSystem_X24Defs_X55ser {
  "id": DocSystem_X24Defs_X55ser_Properties_Id;
  "email": DocSystem_X24Defs_X55ser_Properties_Email;
  "displayName"?: DocSystem_X24Defs_X55ser_Properties_DisplayName;
  "role"?: DocSystem_X24Defs_X55ser_Properties_Role;
}

export type DocSystem_X24Defs_X55X55ID = string;

export type DocSystem_X24Defs_UTimestamp_Properties_X75nix = number;

export type DocSystem_X24Defs_UTimestamp_Properties_Timezone_AnyOf_ZIndex1 = null;

export type DocSystem_X24Defs_UTimestamp_Properties_Timezone_AnyOf_ZIndex0 = string;

export type DocSystem_X24Defs_UTimestamp_Properties_Timezone =
  DocSystem_X24Defs_UTimestamp_Properties_Timezone_AnyOf_ZIndex0 |
  DocSystem_X24Defs_UTimestamp_Properties_Timezone_AnyOf_ZIndex1;

export type DocSystem_X24Defs_UTimestamp_Properties_Iso = string;

export type DocSystem_X24Defs_UTimestamp_AdditionalProperties = never;

export interface DocSystem_X24Defs_UTimestamp {
  "unix": DocSystem_X24Defs_UTimestamp_Properties_X75nix;
  "iso": DocSystem_X24Defs_UTimestamp_Properties_Iso;
  "timezone"?: DocSystem_X24Defs_UTimestamp_Properties_Timezone;
}

export interface DocSystem {
  "document": DocSystem_Properties_Document;
  "permissions": DocSystem_Properties_Permissions;
  "history": DocSystem_Properties_History;
  "relatedDocuments"?: DocSystem_Properties_RelatedDocuments;
}
